name: CI
on: [push]

jobs: 
  sast_scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan
        run: bandit -ll -ii -r . -f json -o bandit-report.json

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bandit-findings
          path: bandit-report.json
       
  image_scan:
    name: Build Image and Run Image Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -f Dockerfile -t myapp:latest .

      - name: Docker Scout Scan
        run: |
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
          sh install-scout.sh
          echo "${{ secrets.REPO_PASS }}" | docker login -u "${{ secrets.REPO_USER }}" --password-stdin
          docker scout quickview --output sarif > quickview-report.sarif
          docker scout cves --output sarif > cve-report.sarif

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: docker-scout-findings
          path: '*.sarif'

      - name: Tag Docker Image
        run: docker tag myapp:latest sufianadnan/lab10:tagname

      - name: Push Docker Image
        run: docker push sufianadnan/lab10:tagname
